### ISSUE TITLE
alterar o nome do arquivo cucumber.conf.js

### ISSUE THREAD

**Issue by cassioafs** [uLucasFraga/protractor_cucumber#1]
alterar o nome do arquivo cucumber.conf.js para protractor.conf.js (padrão do protractor)

**Comment by uLucasFraga** [comment]
Arquivo renomeado para `protractor.conf.js`.

[commit: f5001b2](https://github.com/uLucasFraga/protractor_cucumber/commit/f5001b29470b5c95694cd991fc702150fa410c3e)
