### ISSUE TITLE
Alterar a validação do teste Then (cucumber)

### ISSUE THREAD

**Issue by cassioafs** [uLucasFraga/protractor_cucumber#2]
verificar se funciona se o Then (validações) funciona dessa forma que estou sugerindo

```
 await page.result.getText().then(text=>{
        expect(text).to.equal('30')
    })

```
 para
`expect(page.result.getText()).to.equal('30')	`
ou
`expect(page.result.getText()).to.eventually.equal('30')	`

**Comment by uLucasFraga** [comment]
Não é possível para: `expect(page.result.getText()).to.equal('30')` pois o **getText() retorna uma promessa**. Então precisamos afirmar o que queremos dizer.

O **chai-as-promised** trabalha com o `.to.eventually.equal('seutexto')`, escrevendo o que realmente queremos dizer.

**Conclusão**:
Para um código mais limpo, podemos trabalhar com o: `expect(page.result.getText()).to.eventually.equal('30')`.

O script foi alterado.

**_observação importante:_**
Se for necessário tratar algo no retorno da **promisse** antes de usar o **expect**, esse código não irá funcionar.

[commit: f5001b2](https://github.com/uLucasFraga/protractor_cucumber/commit/f5001b29470b5c95694cd991fc702150fa410c3e)
