### ISSUE TITLE
Retirar o require de element dentro do PageObject

### ISSUE THREAD

**Issue by cassioafs** [uLucasFraga/protractor_cucumber#3]
No PageObject acredito que não precisa requisitar o element, ele é um objeto global que o protractor disponibiliza
`const { element } = require('protractor')
`

**Comment by uLucasFraga** [comment]
Realmente não se faz necessário o uso do `const { element } = require('protractor')` para um objeto global.

[commit: f5001b2](https://github.com/uLucasFraga/protractor_cucumber/commit/f5001b29470b5c95694cd991fc702150fa410c3e)
