### ISSUE TITLE
cenários sem acentuação

### ISSUE THREAD

**Issue by cassioafs** [uLucasFraga/protractor_cucumber#4]
Os cenários estão sem acentução, porém como os cenários estão em `#language: pt` pode adicionar os acentos normalmente.

**Comment by uLucasFraga** [comment]
Cenários atualizados com a acentuação necessária.

```
Cenário: Fazer cálculos com adição
Dado que eu esteja na tela de cálculos
Quando eu fizer cálculos de adição
Então devo visualizar o resultado da adição
```
Os outros cenários também foram atualizados.
[commit: f5001b2](https://github.com/uLucasFraga/protractor_cucumber/commit/f5001b29470b5c95694cd991fc702150fa410c3e)
